# Generated by Django 4.0.3 on 2024-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='soldproducttype',
        ),
        migrations.AlterField(
            model_name='sold',
            name='producttype',
            field=models.CharField(blank=True, choices=[('Local Container', ' Local Container'), ('Public Container', 'Public Container')], default='Local Container', max_length=100, null=True),
        ),
    ]
