# Generated by Django 4.0.3 on 2024-08-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Phone2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Phone2',
        ),
    ]
