# Generated by Django 4.0.3 on 2024-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sold_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='producttype',
            field=models.CharField(choices=[('Local Container', ' Local Container'), ('Public Container', 'Public Container')], default='Local Container', max_length=100, null=True),
        ),
    ]
