# Generated by Django 4.0.3 on 2024-08-13 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customer_phone2_remove_supplier_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
