# Generated by Django 4.0.3 on 2024-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sold_producttype_sold_productype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='productype',
        ),
        migrations.AddField(
            model_name='sold',
            name='soldproductype1',
            field=models.CharField(choices=[('Local Container', ' Local Container'), ('Public Container', 'Public Container')], default='Local Container', max_length=100, null=True),
        ),
    ]
