# Generated by Django 4.0.3 on 2024-08-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_phone2_supplier_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppaybill',
            name='paybillcatogory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paybillcatogory'),
        ),
    ]
