# Generated by Django 4.0.3 on 2024-08-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_soldproductype1_sold_posproductype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='posproductype',
        ),
    ]
