# Generated by Django 4.0.3 on 2024-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_temppaybill_paybillcatogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temppaybill',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='reporttype',
            field=models.CharField(blank=True, choices=[('COMMISION', 'COMMISION'), ('DISCOUNT', 'DISCOUNT'), ('FUND TRANSFER', 'FUND TRANSFER'), ('CORPORATE', 'CORPORATE'), ('FUND REVERSE', 'FUND REVERSE')], max_length=800, null=True),
        ),
    ]
