# Generated by Django 4.0.3 on 2024-08-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_temppaybill_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='corportepay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.corportepay'),
        ),
    ]
