# Generated by Django 4.0.3 on 2024-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sold_conainertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentryrecord',
            name='conainertype',
            field=models.CharField(choices=[('Local Container', ' Local Container'), ('Public Container', 'Public Container')], default='Local Container', max_length=100, null=True),
        ),
    ]
