# Generated by Django 4.0.3 on 2024-03-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_bill_smssend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrentry',
            name='UserItem',
        ),
    ]
