# Generated by Django 4.0.3 on 2024-04-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_remove_mrentry_useritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corportepay',
            old_name='suppiler',
            new_name='suppilier',
        ),
    ]
