# Generated by Django 4.0.3 on 2024-04-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_rename_suppiler_corportepay_suppilier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corportepay',
            old_name='suppilier',
            new_name='supplier',
        ),
    ]
