# Generated by Django 4.0.3 on 2024-04-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_rename_suppilier_corportepay_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='mrentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mrentry'),
        ),
    ]
