# Generated by Django 4.0.3 on 2024-04-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_dailyreport_mrentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplierbalacesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('corporatepay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporatepay', to='core.bill')),
                ('mrentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrentry', to='core.order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='core.supplier')),
            ],
        ),
    ]
