# Generated by Django 4.0.3 on 2024-04-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_supplierbalacesheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supplierbalacesheet',
            new_name='supplierbalancesheet',
        ),
    ]
