# Generated by Django 4.0.3 on 2024-04-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_supplierbalancesheet_mrentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbalancesheet',
            name='mrentry',
        ),
        migrations.AddField(
            model_name='supplierbalancesheet',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrentry', to='core.mrentry'),
        ),
    ]
