# Generated by Django 4.0.3 on 2024-04-04 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_supplierbalancesheet_mrentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbalancesheet',
            name='mrentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrentry', to='core.mrentry'),
        ),
    ]
