# Generated by Django 4.0.3 on 2024-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_alter_supplierbalancesheet_mrentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbalancesheet',
            name='duebalanceadd',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
