# Generated by Django 4.0.3 on 2024-04-09 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_supplierbalancesheet_duebalanceadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbalancesheet',
            name='corporatepay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporatepay', to='core.corportepay'),
        ),
    ]
