# Generated by Django 4.0.3 on 2024-04-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_alter_supplierbalancesheet_corporatepay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supplierbalancesheet',
        ),
    ]
