# Generated by Django 4.0.3 on 2024-04-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_delete_supplierbalancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplierbalancesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, null=True)),
                ('duebalanceadd', models.PositiveIntegerField(default=0, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('corporatepay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporatepay', to='core.corportepay')),
                ('mrentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrentry', to='core.mrentry')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='core.supplier')),
            ],
        ),
    ]
