# Generated by Django 4.0.3 on 2024-04-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_supplierbalancesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbalancesheet',
            name='corporatepay',
        ),
        migrations.AddField(
            model_name='supplierbalancesheet',
            name='corportepay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corportepay', to='core.corportepay'),
        ),
    ]
