# Generated by Django 4.0.3 on 2024-04-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0140_remove_supplierbalancesheet_corporatepay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockquantity', models.PositiveIntegerField(default=0)),
                ('changequanitity', models.PositiveIntegerField(default=0)),
                ('reporttype', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
