# Generated by Django 4.0.3 on 2024-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_plreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='plreport',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
