# Generated by Django 4.0.3 on 2024-05-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_dailyreport_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ('order',)},
        ),
    ]
