# Generated by Django 4.0.3 on 2024-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_alter_dailyreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={},
        ),
        migrations.AddField(
            model_name='corportepay',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
