# Generated by Django 4.0.3 on 2024-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_alter_dailyreport_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybill',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='reporttype',
            field=models.CharField(blank=True, choices=[('COMMISION', 'COMMISION'), ('DISCOUNT', 'DISCOUNT'), ('FUND TRANSFER', 'FUND TRANSFER')], max_length=800, null=True),
        ),
    ]
