# Generated by Django 4.0.3 on 2024-06-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_paybill_datetime_alter_dailyreport_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
