# Generated by Django 4.0.3 on 2024-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
