# Generated by Django 4.0.3 on 2024-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_customerbalacesheet_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnn',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
