# Generated by Django 4.0.3 on 2024-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_returnn_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='plreport',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
