# Generated by Django 4.0.3 on 2024-06-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_plreport_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='datetime',
        ),
        migrations.AddField(
            model_name='bill',
            name='ChequeNo',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='ClearingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bankname',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='brunchname',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='issueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
