# Generated by Django 4.0.3 on 2024-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_bill_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('CASH ', 'CASH'), ('BANK', 'BANK'), ('BOTH', 'BOTH')], default='CASH', max_length=50, null=True),
        ),
    ]
