# Generated by Django 4.0.3 on 2024-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ClearingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
