# Generated by Django 4.0.3 on 2024-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_alter_bill_clearingdate_alter_bill_issuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plreport',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plreport',
            name='reporttype',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
