# Generated by Django 4.0.3 on 2024-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_plreport_price_alter_plreport_reporttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plreport',
            old_name='price',
            new_name='costprice',
        ),
        migrations.AddField(
            model_name='plreport',
            name='price1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plreport',
            name='price2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
