# Generated by Django 4.0.3 on 2024-06-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_sold_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plreport',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
    ]
