# Generated by Django 4.0.3 on 2024-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_alter_plreport_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentry',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
