# Generated by Django 4.0.3 on 2024-06-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_mrentry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='plreport',
            name='mrentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mrentry'),
        ),
    ]
