# Generated by Django 4.0.3 on 2024-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_plreport_mrentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbalancesheet',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
