# Generated by Django 4.0.3 on 2024-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_supplierbalancesheet_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentryrecord',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
