# Generated by Django 4.0.3 on 2024-06-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_mrentryrecord_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
