# Generated by Django 4.0.3 on 2024-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_remove_product_added_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='groupname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
