# Generated by Django 4.0.3 on 2024-07-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_temppaybill_datetime_alter_dailyreport_reporttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
